from enum import Enum


class AdditionalLocationInfo(str, Enum):
    AS_INSTRUCTED = "AS_INSTRUCTED"
    CARPORT = "CARPORT"
    CUSTOMER_PICKUP = "CUSTOMER_PICKUP"
    DECK = "DECK"
    DOOR_PERSON = "DOOR_PERSON"
    FRONT_DESK = "FRONT_DESK"
    FRONT_DOOR = "FRONT_DOOR"
    GARAGE = "GARAGE"
    GUARD = "GUARD"
    MAIL_ROOM = "MAIL_ROOM"
    MAIL_SLOT = "MAIL_SLOT"
    MAILBOX = "MAILBOX"
    MC_BOY = "MC_BOY"
    MC_GIRL = "MC_GIRL"
    MC_MAN = "MC_MAN"
    MC_WOMAN = "MC_WOMAN"
    NEIGHBOR = "NEIGHBOR"
    OFFICE = "OFFICE"
    OUTBUILDING = "OUTBUILDING"
    PATIO = "PATIO"
    PORCH = "PORCH"
    REAR_DOOR = "REAR_DOOR"
    RECEPTIONIST = "RECEPTIONIST"
    RECEIVER = "RECEIVER"
    SECURE_LOCATION = "SECURE_LOCATION"
    SIDE_DOOR = "SIDE_DOOR"

    def __str__(self) -> str:
        return str(self.value)
