from enum import Enum


class ItemApprovalStatus(str, Enum):
    PENDING_SELLING_PARTNER_APPROVAL = "PENDING_SELLING_PARTNER_APPROVAL"
    PROCESSING_SELLING_PARTNER_APPROVAL = "PROCESSING_SELLING_PARTNER_APPROVAL"
    PENDING_AMAZON_APPROVAL = "PENDING_AMAZON_APPROVAL"
    APPROVED = "APPROVED"
    APPROVED_WITH_CHANGES = "APPROVED_WITH_CHANGES"
    DECLINED = "DECLINED"

    def __str__(self) -> str:
        return str(self.value)
