from enum import Enum


class ContentModuleType(str, Enum):
    STANDARD_COMPANY_LOGO = "STANDARD_COMPANY_LOGO"
    STANDARD_COMPARISON_TABLE = "STANDARD_COMPARISON_TABLE"
    STANDARD_FOUR_IMAGE_TEXT = "STANDARD_FOUR_IMAGE_TEXT"
    STANDARD_FOUR_IMAGE_TEXT_QUADRANT = "STANDARD_FOUR_IMAGE_TEXT_QUADRANT"
    STANDARD_HEADER_IMAGE_TEXT = "STANDARD_HEADER_IMAGE_TEXT"
    STANDARD_IMAGE_SIDEBAR = "STANDARD_IMAGE_SIDEBAR"
    STANDARD_IMAGE_TEXT_OVERLAY = "STANDARD_IMAGE_TEXT_OVERLAY"
    STANDARD_MULTIPLE_IMAGE_TEXT = "STANDARD_MULTIPLE_IMAGE_TEXT"
    STANDARD_PRODUCT_DESCRIPTION = "STANDARD_PRODUCT_DESCRIPTION"
    STANDARD_SINGLE_IMAGE_HIGHLIGHTS = "STANDARD_SINGLE_IMAGE_HIGHLIGHTS"
    STANDARD_SINGLE_IMAGE_SPECS_DETAIL = "STANDARD_SINGLE_IMAGE_SPECS_DETAIL"
    STANDARD_SINGLE_SIDE_IMAGE = "STANDARD_SINGLE_SIDE_IMAGE"
    STANDARD_TECH_SPECS = "STANDARD_TECH_SPECS"
    STANDARD_TEXT = "STANDARD_TEXT"
    STANDARD_THREE_IMAGE_TEXT = "STANDARD_THREE_IMAGE_TEXT"

    def __str__(self) -> str:
        return str(self.value)
